name: OpenELP Release

on:
  push:
    branches:
      - release/*

jobs:
  build_windows_installer:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Cache PCRE2
        uses: actions/cache@v4
        with:
          path: ${{runner.workspace}}\build\pcre-prefix\src\pcre2-10.42.tar.gz
          key: pcre2-10.42
      - name: Clone project
        uses: actions/checkout@v4
      - name: Create build environment
        shell: bash
        working-directory: ${{runner.workspace}}
        run: mkdir -p build
      - name: Configure project
        working-directory: ${{runner.workspace}}\build
        run: >
          cmake ${{github.workspace}}
          -Werror=dev
          -Werror=deprecated
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTING:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=ON
          -DCMAKE_PROGRAM_PATH:PATH="${{runner.workspace}}\doxygen"
          -DCMAKE_C_FLAGS="/WX /experimental:external /external:anglebrackets /external:W0"
          -DCMAKE_EXE_LINKER_FLAGS="/WX"
          -DCMAKE_SHARED_LINKER_FLAGS="/WX"
          -DCMAKE_STATIC_LINKER_FLAGS="/WX"
          -DOPENELP_DOC_HTMLHELP:BOOL=OFF
      - name: Build PCRE2
        run: cmake --build ${{runner.workspace}}\build --config Release -j2 -t pcre
      - name: Build project
        run: cmake --build ${{runner.workspace}}\build --config Release -j2
      - name: Package project
        run: cmake --build ${{runner.workspace}}\build --config Release -j2 -t package
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: OpenELP-win64
          path: ${{runner.workspace}}\build\OpenELP-*-win64.exe
